### ISSUE TITLE
Como usuario quiero poder resolver mis dudas

### ISSUE THREAD

**Issue by dqLaptop** [CIFP-Virgen-de-Gracia/donantesSangrePuertollano#30]
Interfaz
- [x] Crear wireframes
- [x] Crear estructura para añadir la información de las preguntas frecuentes
- [x] Añadir estilos

Front
- [x] Crear un servicio para obtener un todas las preguntas y sus respuestas.

Back
- [x] Crear una api para obtener toda la información sobre las preguntas.

Wireframes:

![Image](https://user-images.githubusercontent.com/113903195/227378676-255b2e29-7333-4268-9fb7-bc4ef3993d7d.png)

![Image](https://user-images.githubusercontent.com/113903195/227378675-2532f475-eb26-4cf2-af59-5b87c5ec7166.png)

![Image](https://user-images.githubusercontent.com/113903195/227378677-240dd762-b6dd-4e3a-97ae-210129c0f58a.png)

Resultado Final:

![Image](https://user-images.githubusercontent.com/113903195/227633323-35abb174-2db9-480b-a7e3-d28a6546f48e.JPG)

![Image](https://user-images.githubusercontent.com/113903195/227633322-4473a137-5ed4-4f2f-bc00-6078389614fa.JPG)

![Image](https://user-images.githubusercontent.com/113903195/227633679-633a91dc-9d82-43a3-b7ea-a3d3b31c61af.png)

**Comment by ciclos** [comment]
- Esto es un FAQ? Haz lo Wireframes, que sepa yo la embargadura de esta tarea

**Comment by dqLaptop** [comment]
Lo que voy a realizar en esa tarjeta son las Faqs en las que voy crear la
interfaz con las preguntas que tienen en su página web pero implementado la
parte back y front para que si tienen que eliminar añadir o editar para que
puedan hacerlo pero en cuanto pueda hago los wireframes y los subo para que
veas a lo que me estoy refiriendo
