### ISSUE TITLE
Como donante quiero poder tener un chat para comunicarme con el administrador y otros donantes para resolver mis dudas

### ISSUE THREAD

**Issue by dqLaptop** [CIFP-Virgen-de-Gracia/donantesSangrePuertollano#36]
Back

- [x] Método para realizar la conexión del usuario que este registrado
- [x] Método para la realizar la desconexión de un usuario que este registrado
- [x] Método para enviar y recibir mensajes 

Front
- [x] Creación de un servicio para el socket
- [x] Creación de un modulo y componente
- [x] Creación de un método para emitir el mensaje
- [x] Creación de un método para recibir los mensajes
- [x]  Creacion de un metodo para poder visualizar a los usuarios conectados y desconectados

Interfaz
- [x] Creación de wireframes
- [x] Input para escribir el mensaje
- [x] Zona de visualización de las personas que están conectadas
- [x] Zona de visualización de los mensajes escritos en el chat

Wireframes:

![Image](https://user-images.githubusercontent.com/113903195/232326695-18bbe848-7064-4d51-9cc8-eb99d97db4ef.png)

![Image](https://user-images.githubusercontent.com/113903195/232326631-eb0bb802-0568-4063-b834-adfb9833d6b6.png)

![Image](https://user-images.githubusercontent.com/113903195/232326630-cc71d783-129d-4c18-b296-491f8ad93a7a.png)

Resultado final:

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/113903195/156e696b-6fdf-406d-a44c-31944bd46d18)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/113903195/ecaf355c-6f56-4a72-8cb9-be8cbfd0e667)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/113903195/21a96951-24b6-4051-bae1-8ff790e3c941)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/113903195/6f9f1d6a-61fc-4ccb-83fc-84e06e6d99c7)

**Comment by ciclos** [comment]
- Uff, esto es una funcionalidad bastante grande, si te atreves, adelante!

**Comment by dqLaptop** [comment]
La estuve viendo con Fernando y he estado viendo vídeos sobre el asunto,
pero como dices tiene mucha tela y estuve luego reconsiderándola
