### ISSUE TITLE
Como donantes quiero ver una guia para los donantes (donación de medula)

### ISSUE THREAD

**Issue by Alextorres20** [CIFP-Virgen-de-Gracia/donantesSangrePuertollano#42]
Toda esa información se encontrará en la pestaña de "Informacion".
Esta pagina de informacion contendra todo lo debe saber sobre la donacion de Medula Osea, como es el proceso y guia de Donantes y Un mapa de España que te indica en que regiones hay hospitales que puedes donar Medula Osea

**_Mis Wareframes:_**

> **Formato PC en la pestaña de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/187fafbb-b81f-4cb1-9c8a-f3e830eb44fe)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/b5465c41-8eee-4bde-b632-3e812b9a0449)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/46ec75fa-0482-4f60-9410-c932a2f06dff)

> **Formato Movil en la pestaña de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/aff82265-3cf1-4eca-a131-9505c9f0cc01)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/da707fa8-e5d4-45d5-994b-512676bda21a)

> **Formato PC en la pestaña de Mapa de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/d0157b78-c513-4c27-b161-8afd8b4ecbc9)

> **Formato Movil en la pestaña de Mapa de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/9e13152e-419c-4fa4-b603-bc77b7c6b4f4)

**_Mis Resultados:_**

> **Formato PC en la pestaña de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/ede886b3-001f-4cfc-9de9-130487b5b74b)
![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/e38fb0e6-965f-4c3b-b6c3-8bceb9e49eb6)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/d1b62372-c4e0-4af4-9b08-5478c96f136e)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/dbc5729e-725c-46cf-96f7-e7703bfe4698)

> **Formato Movil en la pestaña de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/a8156243-8c2b-4ef4-b224-c93857a5942b)
![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/df32231a-d070-4ebb-b9bf-eae78f3d5886)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/fb7d8af0-94dc-4ebb-ae89-69121ebf11a4)

> **Formato PC en la pestaña de Mapa de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/6b2bc208-2d7e-45bc-a3dc-85387e144b0f)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/ad52dfd3-f5e3-4281-a04e-5303cfdc5c10)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/559dea03-a7ce-4cb2-89d9-4f98a0852df3)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/81bc2533-db9c-4d1a-bcd7-5d51063c5f39)

> **Formato Movil en la pestaña de Mapa de Medula Osea:**

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/d5b28059-b06a-4e31-994b-f0d32fcc9b5e)
![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/b2e7f433-0d5c-4d04-b161-7360cdf759fe)

![Image](https://github.com/CIFP-Virgen-de-Gracia/donantesSangrePuertollano/assets/35683984/ea3b8e3a-fb2b-4ce5-8856-1a0b71696224)

**Comment by ciclos** [comment]
Esto es el test de donación de sangre, pero para medula, no?
