### ISSUE TITLE
D-La aplicación en una frase y quienes somos

### ISSUE THREAD

**Issue by ciclos** [CIFP-Virgen-de-Gracia/donantesSangrePuertollano#45]

**Comment by ciclos** [comment]
Porque la parte de Alicia es diferente?

**Comment by aliciafdezc** [comment]
No sabía que tenían que ser todas exactamente iguales. Hemos usado todos la misma plantilla pero yo quise usar otros colores y añadir algunos detalles para la mía.

**Comment by ciclos** [comment]
Vale, lo suyo es que o todos iguales o alguna coherencia si vais a usar colores distintos, pero parece que te han contratado aparte ( es el TOC de las interfaces, ya sabéis... ).

**Comment by aliciafdezc** [comment]
Si le pongo los mismos colores que los demás y los bordes rectos ¿Estaría bien?

**Comment by ciclos** [comment]
Dejalo así, era un comentario para tener en cuenta en los sucesivo, pero no tiene tanta importancia.
